import React, { Component } from 'react';

const townsByProvince = {
    "Eastern Cape": [
      "Alice",
      "Butterworth",
      "East London",
      "Graaff-Reinet",
      "Grahamstown",
      "King Williams Town",
      "Mthatha",
      "Port Elizabeth",
      "Queenstown",
      "Uitenhage",
      "Zwelitsha",
    ],

    "Free State": [
      "Bethlehem",
      "Bloemfontein",
      "Jagersfontein",
      "Kroonstad",
      "Odendaalsrus",
      "Parys",
      "Phuthaditjhaba",
      "Sasolburg",
      "Virginia",
      "Welkom",
    ],

    Gauteng: [
      "Benoni",
      "Boksburg",
      "Brakpan",
      "Carletonville",
      "Germiston",
      "Johannesburg",
      "Krugersdorp",
      "Pretoria",
      "Randburg",
      "Randfontein",
      "Roodepoort",
      "Soweto",
      "Springs",
      "Vanderbijlpark",
      "Vereeniging",
    ],

    "KwaZulu-Natal": [
      "Durban",
      "Empangeni",
      "Ladysmith",
      "Newcastle",
      "Pietermaritzburg",
      "Pinetown",
      "Ulundi",
      "Umlazi",
    ],

    Limpopo: [
      "Giyani",
      "Lebowakgomo",
      "Musina",
      "Phalaborwa",
      "Polokwane",
      "Seshego",
      "Sibasa",
      "Thabazimbi",
    ],

   Mpumalanga: [
        "Amersfoort",
        "Amsterdam",
        "Badplaas",
        "Balfour",
        "Barberton",
        "Belfast (eMakhazeni)",
        "Bethal",
        "Breyten",
        "Bushbuckridge",
        "Carolina",
        "Chrissiesmeer",
        "Delmas",
        "Dullstroom - Emnotweni",
        "Ermelo",
        "Graskop",
        "Greylingstad",
        "Hazyview",
        "Hectorspruit",
        "Hendrina",
        "Kaapmuiden",
        "Kaapsche Hoop",
        "Kinross",
        "Komatipoort",
        "KrielOgies",
        "Kruger National Park",
        "Kwaggafontein & Siyabuswa",
        "KwaMhlanga",
        "Loopspruit",
        "Machadodorp & the Kwena Basin",
        "Malelane",
        "Marloth Park",
        "Mashishing (previously Lydenburg)",
        "Middelburg (including Botshabelo)",
        "Morgenzon",
        "Nelspruit (Mbombela)",
        "Perdekop",
        "Piet Retief (eMkhondo)",
        "Pilgrims Rest",
        "Roossenekal",
        "Sabie",
        "Schoemanskloof",
        "Secunda (including Trichardt)",
        "Standerton",
        "Volksrust",
        "Wakkerstroom",
        "Waterval Boven (Emgwenya) incl. Waterval Onder",
        "White River",
        "Witbank (eMalahleni)"
      ],
      

    "North West": [
      "Klerksdorp",
      "Mahikeng",
      "Mmabatho",
      "Potchefstroom",
      "Rustenburg",
    ],

    "Northern Cape": [
        "Barkly West",
        "Campbell",
        "Delportshoop",
        "Douglas",
        "Griquatown",
        "Hartswater",
        "Jan Kempdorp",
        "Kimberley",
        "Modder River",
        "Ulco",
        "Warrenton",
        "Windsorton",
        "Green Kalahari",
        "Andriesvale",
        "Askham",
        "Augrabies",
        "Danielskuil",
        "Groblershoop",
        "Kakamas",
        "Kanoneiland",
        "Kathu",
        "Keimoes",
        "Kenhardt",
        "Kuruman",
        "Lime Acres",
        "Louisvale",
        "Mier",
        "Olifantshoek",
        "Onseepkans",
        "Postmasburg",
        "Putsonderwater",
        "Riemvasmaak",
        "Rietfontein",
        "Upington",
        "Namaqualand",
        "Aggeneys",
        "Alexander Bay",
        "Carolusberg",
        "Concordia",
        "Garies",
        "Hondeklip",
        "Kamieskroon",
        "Kleinzee",
        "Nababeep",
        "Nieuwoudtville",
        "Okiep",
        "Pella",
        "Pofadder",
        "Port Nolloth",
        "Soebatsfontein",
        "Springbok",
        "Steinkopf",
        "Upper Karoo",
        "Britstown",
        "Colesberg",
        "Copperton",
        "De Aar",
        "Hanover",
        "Hopetown",
        "Hutchinson",
        "Loxton",
        "Marydale",
        "Norvalspont",
        "Noupoort",
        "Orania",
        "Petrusville",
        "Philipstown",
        "Prieska",
        "Richmond",
        "Strydenburg",
        "Vanderkloof",
        "Victoria West",
        "Vosburg"
      ],
      

    "Western Cape": [
      "Bellville",
      "Cape Town",
      "Constantia",
      "George",
      "Hopefield",
      "Oudtshoorn",
      "Paarl",
      "Simons Town",
      "Stellenbosch",
      "Swellendam",
      "Worcester",
    ],

    "Orange Free State": [
      "Allanridge",
      "Bethlehem",
      "Bloemfontein",
      "Boshof",
      "Bothaville",
      "Botshabelo",
      "Brandfort",
      "Bultfontein",
      "Clocolan",
      "Deneysville",
      "Dewetsdorp",
      "Ficksburg",
      "Frankfort",
      "Harrismith",
      "Heilbron",
      "Hennenman",
      "Hoopstad",
      "Koffiefontein",
      "Koppies",
      "Kroonstad",
      "Kutloanong",
      "Ladybrand",
      "Lindley",
      "Marquard",
      "Parys",
      "Phuthaditjhaba",
      "Reitz",
      "Sasolburg",
      "Senekal",
      "Thaba Nchu",
      "Theunissen",
      "Trompsburg",
      "Ventersburg",
      "Viljoenskroon",
      "Villiers",
      "Virginia",
      "Vrede",
      "Vredefort",
      "Welkom",
      "Wesselsbron",
      "Winburg",
      "Zastron",
    ],

    Transvaal: [
      "Johannesburg",
      "Alberton",
      "Germiston",
      "Boksburg",
      "Benoni",
      "Kempton Park",
      "Randburg",
      "Roodepoort",
      "Westonaria",
      "Oberholzer",
      "Randfontein",
      "Krugersdorp",
      "Brakpan",
      "Springs",
      "Nigel",
      "Delmas",
      "Pretoria",
      "Wonderboom",
      "Soshanguve",
      "Cullinan",
      "Vanderbijlpark",
      "Vereeniging",
      "Heidelberg",
      "Balfour",
      "Standerton",
      "Hoëveldrif (Highveld Ridge)",
      "Bethal",
      "Volksrust",
      "Amersfoort",
      "Wakkerstroom",
      "Piet Retief",
      "Ermelo",
      "Carolina",
      "Bronkhorstspruit",
      "Witbank",
      "Middelburg",
      "Belfast",
      "Waterval-Boven",
      "Groblersdal",
      "Moutse (main town Dennilton)",
      "Nelspruit",
      "Barberton",
      "Witrivier",
      "Pelgrimsrus (main town Sabie)",
      "Lydenburg",
      "Letaba (main town Tzaneen)",
      "Phalaborwa",
      "Soutpansberg (main town Louis Trichardt)",
      "Messina",
      "Pietersburg",
      "Potgietersrus",
      "Waterberg (main town Nylstroom)",
      "Ellisras",
      "Thabazimbi",
      "Warmbad",
      "Brits",
      "Rustenburg",
      "Swartruggens",
      "Marico",
      "Koster",
      "Ventersdorp",
      "Coligny",
      "Lichtenburg",
      "Delareyville",
      "Potchefstroom",
      "Klerksdorp",
      "Wolmaransstad",
      "Schweizer-Reneke",
      "Bloemhof",
      "Christiana",
    ],

    Transkei: [
      "Alice",
      "Butterworth",
      "East London",
      "Graaff-Reinet",
      "Grahamstown",
      "King Williams Town",
      "Mthatha",
      "Port Elizabeth",
      "Queenstown",
      "Uitenhage",
      "Zwelitsha",
    ],

    Bophuthatswana: [
      "Bafokeng",
      "Ditsobotla",
      "Ganyesa",
      "Lehurutshe",
      "Madikwe",
      "Mankwe",
      "Molopo",
      "Moretele",
      "Odi",
      "Taung",
      "Thaba 'Nchu",
      "Tlhaping-Tlharo",
      "Ga-Rankuwa",
      "Mabopane",
      "Mafikeng",
      "Mmabatho", // The capital
      "Mogwase",
      "Temba",
      "Tlhabane",
    ],
    Venda: [
      "Giyani",
      "Lebowakgomo",
      "Musina",
      "Phalaborwa",
      "Polokwane",
      "Seshego",
      "Sibasa",
      "Thabazimbi",
      "Thohoyandou",
    ],

    Ciskei: [
      "Alice",
      "Butterworth",
      "East London",
      "Graaff-Reinet",
      "Grahamstown",
      "King Williams Town",
      "Mthatha",
      "Port Elizabeth",
      "Queenstown",
      "Uitenhage",
      "Zwelitsha",
    ],
  };

export default townsByProvince;